# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d14625f3888e47e877a5b0cc302e066625ccccce10236935ed4f3d267b4c4c82139c9f21432c5ce4f4b1c8e9d7e77214c196a913e92b7c15a4b40e5a08f0bc

test:
  secret_key_base: 237487084f984e2ce58537ea063143e724876f195f425d09079f59a2b10391bee75c7669c249da1f3d44a24c1ce7f160f2ed8720880408d817cb04842331e09e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fd40b6412231d72e38995be5822b4cad41e068755d9ef1e4a667a8bf7776b6819d218e74e4b2b9064fbac27bcebe968dc70984ced4d2f3612ae5a9d6926b3265
    # <%= ENV["SECRET_KEY_BASE"] %>
